name: "Bug"
description: "报错啦报错啦"
labels: ["· Bug"]
body:
  - type: textarea
    id: "disc"
    attributes:
      label: 描述
      description: "详细内容。"
    validations:
      required: true
  - type: textarea
    id: "files"
    attributes:
      label: "[可选]附件"
      description: "上传附件"
      placeholder: "将文件直接拖至这里上传。"
